export const getStyles = (t, isDark) => ({

  container: {
    display: "flex",
    height: "100vh",
    backgroundColor: t.bg.primary,
    color: t.text.primary,
    fontFamily: "'Poppins', sans-serif",
    width: "100%",
    maxWidth: "100%",
    overflow: "hidden",
  },
  contentWrap: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    minWidth: 0,
    height: "100vh",
    overflow: "hidden",
  },

  /* Sidebar */
  sidebar: {
    width: "220px",
    flexShrink: 0,
    backgroundColor: t.bg.secondary,
    borderRight: `1px solid ${t.border}`,
    padding: "20px 0 0",
    position: "sticky",
    top: 0,
    height: "100vh",
    overflowY: "auto",
    display: "flex",
    flexDirection: "column",
  },
  sidebarHeader: {
    padding: "0 20px 16px",
    borderBottom: `1px solid ${t.border}`,
    marginBottom: "12px",
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  sidebarLogo: {
    width: "32px",
    height: "32px",
    borderRadius: "8px",
    background: "linear-gradient(135deg, #6366f1, #8b5cf6)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  sidebarTitle: {
    fontSize: "14px",
    fontWeight: "700",
    color: t.text.primary,
  },
  sidebarSubtitle: {
    fontSize: "10px",
    fontWeight: "600",
    color: t.text.tertiary,
    textTransform: "uppercase",
    letterSpacing: "0.5px",
  },
  navGroup: {
    padding: "0 12px",
    marginBottom: "8px",
  },
  navGroupLabel: {
    fontSize: "9px",
    fontWeight: "700",
    color: t.text.tertiary,
    textTransform: "uppercase",
    letterSpacing: "0.8px",
    padding: "8px 8px 4px",
  },
  navItem: (active) => ({
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "7px 10px",
    borderRadius: "8px",
    fontSize: "12px",
    fontWeight: active ? "600" : "500",
    color: active ? t.accent : t.text.secondary,
    backgroundColor: active ? `${t.accent}10` : "transparent",
    cursor: "pointer",
    transition: "all 0.15s",
    border: "none",
    width: "100%",
    textAlign: "left",
    fontFamily: "inherit",
  }),

  /* Main content */
  content: {
    flex: 1,
    padding: "32px 40px",
    maxWidth: "100%",
    width: "100%",
    overflowY: "auto",
    boxSizing: "border-box",
    overflowWrap: "break-word",
  },
  pageTitle: {
    fontSize: "28px",
    fontWeight: "800",
    color: t.text.primary,
    letterSpacing: "-0.5px",
    marginBottom: "4px",
  },
  pageDesc: {
    fontSize: "14px",
    color: t.text.secondary,
    marginBottom: "36px",
    lineHeight: 1.6,
  },
  section: {
    marginBottom: "28px",
  },
  sectionHeader: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    marginBottom: "16px",
    paddingBottom: "8px",
    borderBottom: `1.5px solid ${t.border}`,
  },
  sectionNumber: {
    width: "24px",
    height: "24px",
    borderRadius: "6px",
    background: `linear-gradient(135deg, ${t.accent}, ${t.accent}88)`,
    color: "#fff",
    fontSize: "11px",
    fontWeight: "700",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  sectionTitle: {
    fontSize: "18px",
    fontWeight: "700",
    color: t.text.primary,
    letterSpacing: "-0.3px",
  },
  paragraph: {
    fontSize: "13px",
    color: t.text.secondary,
    lineHeight: 1.6,
    marginBottom: "10px",
  },
  subTitle: {
    fontSize: "15px",
    fontWeight: "600",
    color: t.text.primary,
    marginBottom: "10px",
    marginTop: "24px",
  },
  subSubTitle: {
    fontSize: "13px",
    fontWeight: "600",
    color: t.text.primary,
    marginBottom: "8px",
    marginTop: "18px",
  },

  /* Code block */
  codeBlock: {
    backgroundColor: isDark ? "#0f172a" : "#f1f5f9",
    borderRadius: "10px",
    padding: "14px 18px",
    fontSize: "12px",
    fontFamily: "'SF Mono', 'Consolas', monospace",
    color: isDark ? "#e2e8f0" : "#1e293b",
    overflowX: "auto",
    marginBottom: "16px",
    border: `1px solid ${t.border}`,
    lineHeight: 1.6,
    whiteSpace: "pre",
  },
  inlineCode: {
    backgroundColor: isDark ? "#1e293b" : "#f1f5f9",
    color: isDark ? "#a5b4fc" : "#6366f1",
    padding: "2px 6px",
    borderRadius: "4px",
    fontSize: "12px",
    fontFamily: "'SF Mono', monospace",
  },

  /* Table */
  tableWrap: {
    overflowX: "auto",
    marginBottom: "16px",
    borderRadius: "10px",
    border: `1px solid ${t.border}`,
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
    fontSize: "12px",
    minWidth: "480px",
  },
  th: {
    padding: "10px 14px",
    textAlign: "left",
    fontWeight: "700",
    color: t.text.tertiary,
    backgroundColor: t.bg.tertiary,
    borderBottom: `1px solid ${t.border}`,
    textTransform: "uppercase",
    letterSpacing: "0.5px",
    fontSize: "10px",
  },
  td: {
    padding: "9px 14px",
    borderBottom: `1px solid ${t.borderLight || t.border}`,
    color: t.text.secondary,
  },
  rowAlt: {
    backgroundColor: isDark ? 'rgba(255,255,255,0.02)' : 'rgba(0,0,0,0.015)',
  },
  tdValue: {
    fontWeight: "600",
    color: t.text.primary,
  },

  /* Tags */
  tag: (color) => ({
    display: "inline-block",
    padding: "2px 8px",
    borderRadius: "4px",
    fontSize: "10px",
    fontWeight: "700",
    backgroundColor: `${color}15`,
    color: color,
  }),
  badge: {
    display: "inline-flex",
    alignItems: "center",
    gap: "4px",
    padding: "2px 8px",
    borderRadius: "10px",
    fontSize: "10px",
    fontWeight: "600",
    backgroundColor: `${t.accent}12`,
    color: t.accent,
  },

  /* List */
  list: {
    margin: "0 0 14px 0",
    padding: "0 0 0 18px",
    fontSize: "13px",
    color: t.text.secondary,
    lineHeight: 1.8,
  },
  listItem: {
    marginBottom: "4px",
  },

  /* Tech grid */
  techGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(140px, 1fr))",
    gap: "10px",
    marginBottom: "16px",
  },
  techCard: {
    backgroundColor: t.bg.secondary,
    borderRadius: "10px",
    border: `1px solid ${t.border}`,
    padding: "14px",
    display: "flex",
    flexDirection: "column",
    gap: "4px",
  },
  techName: {
    fontSize: "13px",
    fontWeight: "700",
    color: t.text.primary,
  },
  techUse: {
    fontSize: "10px",
    fontWeight: "500",
    color: t.text.tertiary,
    lineHeight: 1.4,
  },
  techVersion: {
    fontSize: "10px",
    fontWeight: "600",
    color: t.accent,
  },

  /* ER Diagram */
  erDiagram: {
    backgroundColor: t.bg.primary,
    borderRadius: "10px",
    border: `1px solid ${t.border}`,
    padding: "20px 24px",
    fontFamily: "'SF Mono', monospace",
    fontSize: "12px",
    color: t.text.secondary,
    lineHeight: 1.8,
    marginBottom: "16px",
    whiteSpace: "pre",
    overflowX: "auto",
  },

  /* GitHub */
  githubCard: {
    backgroundColor: t.bg.secondary,
    borderRadius: '12px',
    border: `1px solid ${t.border}`,
    padding: '18px 20px',
    marginBottom: '24px',
  },
  githubCardTitle: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    fontSize: '13px',
    fontWeight: '700',
    color: t.text.primary,
    marginBottom: '14px',
    paddingBottom: '10px',
    borderBottom: `1px solid ${t.border}`,
  },
  githubRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    marginBottom: '10px',
    fontSize: '12px',
  },
  githubLabel: {
    fontWeight: '600',
    color: t.text.tertiary,
    minWidth: '70px',
    fontSize: '11px',
    textTransform: 'uppercase',
    letterSpacing: '0.3px',
  },
  githubLink: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    color: t.accent,
    textDecoration: 'none',
    fontWeight: '600',
    fontSize: '12px',
    transition: 'opacity 0.15s',
  },
  githubCloneRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    marginBottom: '8px',
  },
  githubClone: {
    flex: 1,
    fontSize: '11px',
    fontFamily: "'SF Mono', monospace",
    color: t.text.secondary,
    backgroundColor: t.bg.primary,
    padding: '6px 10px',
    borderRadius: '6px',
    border: `1px solid ${t.border}`,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  copyBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '4px',
    padding: '5px 10px',
    borderRadius: '6px',
    border: `1px solid ${t.border}`,
    backgroundColor: t.bg.tertiary,
    color: t.text.secondary,
    fontSize: '11px',
    fontWeight: '600',
    cursor: 'pointer',
    fontFamily: 'inherit',
    whiteSpace: 'nowrap',
    flexShrink: 0,
    transition: 'all 0.15s',
  },

  /* Back link */
  backLink: {
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    fontSize: "12px",
    fontWeight: "600",
    color: t.accent,
    cursor: "pointer",
    border: "none",
    backgroundColor: "transparent",
    fontFamily: "inherit",
    marginBottom: "24px",
    padding: "6px 12px",
    borderRadius: "8px",
    transition: "background 0.15s",
  },
});
