export const getStyles = (
  t,
  isDark,
  isDragging = false,
  isSortableDragging = false,
) => ({
  container: {
    minHeight: "100vh",
    backgroundColor: t.bg.primary,
    color: t.text.primary,
    fontFamily: "'Poppins', sans-serif",
    transition: "background-color 0.3s ease, color 0.3s ease",
    display: "flex",
    flexDirection: "column",
    width: "100%",
    maxWidth: "100%",
    overflowX: "hidden",
  },
  loader: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    minHeight: "100vh",
    fontSize: "14px",
    color: t.text.secondary,
    backgroundColor: t.bg.primary,
    gap: "12px",
  },
  header: {
    backgroundColor: t.bg.glass,
    borderBottom: `1px solid ${t.border}`,
    padding: "0 24px",
    height: "64px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    position: "sticky",
    top: 0,
    zIndex: 50,
    backdropFilter: "blur(16px)",
    WebkitBackdropFilter: "blur(16px)",
    boxShadow: "0 4px 30px rgba(0, 0, 0, 0.03)",
  },
  headerLeft: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
  },
  headerLogo: {
    width: "36px",
    height: "36px",
    borderRadius: "10px",
    background: "linear-gradient(135deg, #6366f1, #8b5cf6)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    boxShadow: "0 4px 12px rgba(99,102,241,0.25)",
  },
  headerRight: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  divider: {
    height: "24px",
    width: "1px",
    backgroundColor: t.border,
    margin: "0 6px",
  },
  main: {
    padding: "12px",
    maxWidth: "1400px",
    margin: "0 auto",
    width: "100%",
    boxSizing: "border-box",
  },
  subHeader: {
    backgroundColor: t.bg.secondary,
    borderBottom: `1px solid ${t.border}`,
    padding: "0 24px",
    display: "flex",
    gap: "24px",
  },
  navTab: (isActive) => ({
    padding: "14px 4px",
    fontSize: "13px",
    fontWeight: "600",
    color: isActive ? t.accent : t.text.secondary,
    borderBottom: `2.5px solid ${isActive ? t.accent : "transparent"}`,
    cursor: "pointer",
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    transition: "all 0.15s ease",
  }),
  metricsCard: {
    backgroundColor: t.bg.secondary,
    borderRadius: "12px",
    border: `1px solid ${t.border}`,
    marginBottom: "12px",
    overflow: "hidden",
  },
  metricsBody: {
    display: "flex",
    alignItems: "center",
    padding: "10px 14px",
    gap: "6px",
    flexWrap: "wrap",
  },
  metricHero: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    padding: "6px 16px 6px 4px",
    flexShrink: 0,
  },
  metricHeroValue: {
    fontSize: "28px",
    fontWeight: "900",
    color: t.text.primary,
    lineHeight: 1,
    letterSpacing: "-1px",
    fontVariantNumeric: "tabular-nums",
  },
  metricHeroLabel: {
    fontSize: "10px",
    fontWeight: "600",
    color: t.text.tertiary,
    maxWidth: "60px",
    textTransform: "uppercase",
    letterSpacing: "0.3px",
    lineHeight: 1.3,
  },
  metricDivider: {
    width: "1px",
    height: "36px",
    backgroundColor: t.border,
    flexShrink: 0,
  },
  metricGroup: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    padding: "0 16px",
    flex: 1,
    minWidth: 0,
  },
  metricGroupLabel: {
    fontSize: "9px",
    fontWeight: "700",
    color: t.text.tertiary,
    textTransform: "uppercase",
    letterSpacing: "0.5px",
    flexShrink: 0,
    width: "40px",
  },
  metricItems: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    flexWrap: "wrap",
  },
  metricPill: {
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    padding: "7px 12px",
    borderRadius: "10px",
    backgroundColor: t.bg.primary,
    border: `1px solid ${t.borderLight || t.border}`,
    whiteSpace: "nowrap",
  },
  metricPillValue: {
    fontSize: "13px",
    fontWeight: "800",
    color: t.text.primary,
    fontVariantNumeric: "tabular-nums",
  },
  metricPillLabel: {
    fontSize: "12px",
    fontWeight: "500",
    color: t.text.tertiary,
  },
  metricTeam: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "0 4px 0 16px",
    cursor: "pointer",
    flexShrink: 0,
    transition: "opacity 0.15s",
  },
  metricTeamValue: {
    fontSize: "16px",
    fontWeight: "800",
    color: t.text.primary,
    fontVariantNumeric: "tabular-nums",
  },
  metricTeamLabel: {
    fontSize: "10px",
    fontWeight: "600",
    color: t.text.tertiary,
    textTransform: "uppercase",
    letterSpacing: "0.3px",
  },
  toolbar: {
    backgroundColor: t.bg.secondary,
    borderRadius: "12px",
    border: `1.5px solid ${t.border}`,
    padding: "12px 14px",
    marginBottom: "12px",
  },
  toolbarContent: {
    display: "flex",
    flexWrap: "wrap",
    gap: "12px",
    alignItems: "center",
    justifyContent: "space-between",
  },
  toolbarLeft: {
    display: "flex",
    gap: "10px",
    alignItems: "center",
    flexWrap: "wrap",
    flex: 1,
  },
  newTicketBtn: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "6px",
    border: "none",
    cursor: "pointer",
    fontWeight: "600",
    fontSize: "13px",
    fontFamily: "inherit",
    padding: "0 18px",
    borderRadius: "10px",
    background: "linear-gradient(135deg, #6366f1, #8b5cf6)",
    color: "#fff",
    height: "38px",
    transition: "all 0.2s ease",
  },
  viewToggle: {
    display: "flex",
    borderRadius: "10px",
    overflow: "hidden",
    border: `1.5px solid ${t.border}`,
    height: "38px",
    boxSizing: "border-box",
    backgroundColor: "transparent",
  },
  viewToggleBtn: (isActive, isLast = false) => ({
    padding: "0 16px",
    borderRadius: 0,
    height: "100%",
    backgroundColor: isActive ? t.accent : "transparent",
    color: isActive ? "#fff" : t.text.tertiary,
    border: "none",
    borderRight: isLast ? "none" : `1.5px solid ${t.border}`,
    boxShadow: "none",
    outline: "none",
  }),
  searchWrapper: {
    position: "relative",
    minWidth: "220px",
    flex: "0 1 320px",
    height: "38px",
  },
  searchIcon: {
    position: "absolute",
    left: "12px",
    top: "50%",
    transform: "translateY(-50%)",
  },
  searchInput: {
    width: "100%",
    padding: "0 12px 0 38px",
    borderRadius: "10px",
    border: `1.5px solid ${t.border}`,
    backgroundColor: t.bg.primary,
    color: t.text.primary,
    fontSize: "13px",
    boxSizing: "border-box",
    height: "38px",
    transition: "border-color 0.2s",
  },
  toolbarRight: {
    display: "flex",
    gap: "8px",
    alignItems: "center",
    flexWrap: "wrap",
    height: "38px",
  },
  filterTriggerBtn: (active) => ({
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    padding: active ? "0 12px 0 14px" : "0 14px",
    borderRadius: "10px",
    height: "38px",
    backgroundColor: active ? `${t.accent}12` : t.bg.tertiary,
    color: active ? t.accent : t.text.secondary,
    border: `1.5px solid ${active ? `${t.accent}40` : t.border}`,
    fontWeight: active ? "600" : "500",
    transition: "all 0.2s ease",
    position: "relative",
    overflow: "hidden",
  }),
  ticketCount: {
    fontSize: "12px",
    color: t.text.tertiary,
    fontWeight: "600",
    paddingLeft: "4px",
  },
  filterPanel: {
    marginTop: "14px",
    paddingTop: "14px",
    borderTop: `1.5px solid ${t.border}`,
    animation: "fadeIn 0.2s ease",
  },
  filterGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))",
    gap: "14px",
    alignItems: "start",
  },
  filterGroup: {
    display: "flex",
    flexDirection: "column",
    gap: "6px",
  },
  filterGroupLabel: {
    fontSize: "10px",
    fontWeight: "700",
    color: t.text.tertiary,
    textTransform: "uppercase",
    letterSpacing: "0.5px",
  },
  filterChips: {
    display: "flex",
    flexWrap: "wrap",
    gap: "6px",
  },
  filterChip: (active, color) => ({
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    padding: "6px 14px",
    borderRadius: "20px",
    fontSize: "12px",
    fontWeight: "600",
    cursor: "pointer",
    border: "none",
    fontFamily: "inherit",
    transition: "all 0.15s ease",
    backgroundColor: active
      ? `${color}18`
      : t.bg.tertiary,
    color: active ? color : t.text.secondary,
    boxShadow: active
      ? `0 0 0 1.5px ${color}40`
      : "none",
  }),
  filterChipDot: (color) => ({
    width: "7px",
    height: "7px",
    borderRadius: "50%",
    backgroundColor: color,
    flexShrink: 0,
  }),
  filterDivider: {
    width: "1px",
    height: "24px",
    backgroundColor: t.border,
    margin: "0 4px",
    flexShrink: 0,
  },
  filterActiveRow: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    flexWrap: "wrap",
    marginTop: "6px",
  },
  filterActiveTag: (color) => ({
    display: "inline-flex",
    alignItems: "center",
    gap: "4px",
    padding: "3px 10px 3px 8px",
    borderRadius: "14px",
    fontSize: "11px",
    fontWeight: "600",
    backgroundColor: `${color}15`,
    color: color,
    border: `1px solid ${color}30`,
  }),
  filterClearBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: "4px",
    padding: "3px 10px",
    borderRadius: "14px",
    fontSize: "11px",
    fontWeight: "600",
    backgroundColor: "transparent",
    color: t.text.tertiary,
    border: `1px solid ${t.border}`,
    cursor: "pointer",
    fontFamily: "inherit",
    transition: "all 0.15s",
  },
  tableWrap: {
    backgroundColor: t.bg.secondary,
    borderRadius: "16px",
    border: `1.5px solid ${t.border}`,
    boxShadow: `0 10px 30px ${t.shadow}`,
    overflow: "hidden",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
    minWidth: "780px",
  },
  th: (isAction = false) => ({
    padding: "10px 14px",
    textAlign: "left",
    fontSize: "11px",
    fontWeight: "700",
    color: t.text.tertiary,
    textTransform: "uppercase",
    letterSpacing: "0.8px",
    backgroundColor: t.bg.tertiary,
    borderBottom: `1.5px solid ${t.border}`,
    ...(isAction ? { width: "100px" } : {}),
  }),
  row: {
    borderBottom: `1px solid ${t.borderLight}`,
    cursor: "pointer",
    transition: "all 0.15s ease",
  },
  td: {
    padding: "10px 14px",
  },
  categoryBadge: {
    fontSize: "10px",
    fontWeight: "600",
    color: t.text.secondary,
    backgroundColor: t.bg.tertiary,
    padding: "3px 8px",
    borderRadius: "6px",
    border: `1px solid ${t.border}`,
  },
  priorityBadge: (color) => ({
    fontSize: "10px",
    fontWeight: "700",
    color: "#fff",
    backgroundColor: color,
    padding: "3px 10px",
    borderRadius: "20px",
  }),
  statusWrapper: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
  },
  statusDot: (color) => ({
    width: "8px",
    height: "8px",
    borderRadius: "50%",
    backgroundColor: color,
    flexShrink: 0,
  }),
  assigneesList: {
    display: "flex",
    alignItems: "center",
    gap: "4px",
    flexWrap: "wrap",
  },
  unassignedText: {
    fontSize: "11px",
    color: t.text.tertiary,
    fontStyle: "italic",
  },
  actionsWrapper: {
    display: "flex",
    gap: "4px",
    justifyContent: "flex-end",
  },
  actionBtn: {
    width: "30px",
    height: "30px",
    borderRadius: "8px",
    backgroundColor: t.bg.tertiary,
    color: t.text.secondary,
    padding: 0,
    border: `1px solid ${t.border}`,
  },
  deleteBtn: {
    width: "30px",
    height: "30px",
    borderRadius: "8px",
    backgroundColor: "transparent",
    color: t.text.tertiary,
    padding: 0,
  },
  emptyState: {
    textAlign: "center",
    padding: "70px 20px",
    color: t.text.tertiary,
  },
  emptyStateIcon: {
    width: "64px",
    height: "64px",
    borderRadius: "16px",
    margin: "0 auto 16px",
    backgroundColor: t.bg.tertiary,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  emptyTitle: {
    fontSize: "15px",
    fontWeight: "600",
    margin: "0 0 4px",
    color: t.text.secondary,
  },
  emptySubtitle: {
    fontSize: "13px",
    margin: "0 0 16px",
  },
  emptyCreateBtn: {
    padding: "0 20px",
    borderRadius: "10px",
    height: "36px",
    background: "linear-gradient(135deg, #6366f1, #8b5cf6)",
    color: "#fff",
  },
  sidePanelBackdrop: {
    position: "fixed",
    inset: 0,
    zIndex: 1000,
    display: "flex",
    justifyContent: "flex-end",
    backgroundColor: "rgba(15, 23, 42, 0.4)",
    backdropFilter: "blur(8px)",
    animation: "fadeIn 0.2s ease",
  },
  sidePanel: {
    width: "100%",
    maxWidth: "580px",
    height: "100%",
    backgroundColor: t.bg.secondary,
    borderLeft: `1px solid ${t.border}`,
    boxShadow: "-10px 0 30px rgba(0, 0, 0, 0.15)",
    display: "flex",
    flexDirection: "column",
    animation: "slideInRight 0.3s cubic-bezier(0.16, 1, 0.3, 1)",
  },
  panelHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "20px 24px",
    borderBottom: `1px solid ${t.border}`,
    backgroundColor: t.bg.secondary,
    position: "sticky",
    top: 0,
    zIndex: 1,
  },
  panelHeaderId: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  panelHeaderIdText: {
    fontSize: "13px",
    fontWeight: "600",
    color: t.text.tertiary,
    fontFamily: "monospace",
    letterSpacing: "0.5px",
  },
  panelHeaderActions: {
    display: "flex",
    gap: "8px",
  },
  panelHeaderEditBtn: {
    padding: "0 14px",
    borderRadius: "8px",
    height: "32px",
    backgroundColor: t.bg.tertiary,
    color: t.text.secondary,
    fontSize: "12px",
    border: `1px solid ${t.border}`,
  },
  panelHeaderDeleteBtn: {
    padding: "0 14px",
    borderRadius: "8px",
    height: "32px",
    backgroundColor: "transparent",
    color: t.danger,
    fontSize: "12px",
    border: `1.5px solid ${isDark ? "rgba(239,68,68,0.2)" : "#fecaca"}`,
  },
  panelHeaderCloseBtn: {
    width: "32px",
    height: "32px",
    borderRadius: "8px",
    backgroundColor: t.bg.tertiary,
    color: t.text.secondary,
    padding: 0,
    border: `1px solid ${t.border}`,
  },
  panelBody: {
    padding: "24px",
    flex: 1,
    overflowY: "auto",
    display: "flex",
    flexDirection: "column",
    gap: "24px",
  },
  panelTitle: {
    fontSize: "22px",
    fontWeight: "700",
    color: t.text.primary,
    margin: "0 0 16px",
    lineHeight: 1.35,
    letterSpacing: "-0.3px",
  },
  propertiesGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "16px 20px",
    padding: "20px",
    borderRadius: "14px",
    backgroundColor: t.bg.primary,
    border: `1px solid ${t.border}`,
  },
  propertyItemValue: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    height: "24px",
  },
  assigneePill: {
    display: "flex",
    alignItems: "center",
    gap: "4px",
    backgroundColor: t.bg.tertiary,
    padding: "2px 8px",
    borderRadius: "12px",
    border: `1px solid ${t.border}`,
  },
  assigneePillText: {
    fontSize: "11px",
    fontWeight: "500",
    color: t.text.primary,
  },
  propertyText: {
    fontSize: "12px",
    fontWeight: "500",
    color: t.text.secondary,
  },
  descriptionBox: {
    fontSize: "14px",
    color: t.text.secondary,
    lineHeight: 1.7,
    backgroundColor: t.bg.primary,
    padding: "16px 20px",
    borderRadius: "12px",
    border: `1px solid ${t.border}`,
    borderLeft: `4px solid ${t.accent}`,
    whiteSpace: "pre-wrap",
    minHeight: "60px",
  },
  commentsHeader: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    borderBottom: `1px solid ${t.border}`,
    paddingBottom: "10px",
  },
  commentInputCard: {
    backgroundColor: t.bg.primary,
    borderRadius: "14px",
    border: `1.5px solid ${t.border}`,
    overflow: "hidden",
    transition: "border-color 0.2s, box-shadow 0.2s",
  },
  commentInputHeader: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "10px 14px 0",
  },
  commentInputTextarea: {
    width: "100%",
    padding: "8px 14px 12px",
    border: "none",
    backgroundColor: "transparent",
    color: t.text.primary,
    fontSize: "13px",
    fontFamily: "inherit",
    resize: "none",
    minHeight: "40px",
    lineHeight: 1.5,
  },
  commentInputFooter: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "4px 8px 8px 14px",
  },
  commentInputHint: {
    fontSize: "11px",
    color: t.text.tertiary,
  },
  commentSendBtn: (hasText) => ({
    width: "32px",
    height: "32px",
    borderRadius: "8px",
    padding: 0,
    backgroundColor: hasText ? t.accent : t.bg.tertiary,
    color: hasText ? "#fff" : t.text.tertiary,
    border: "none",
    cursor: hasText ? "pointer" : "default",
    transition: "all 0.2s",
  }),
  commentItem: {
    display: "flex",
    gap: "10px",
    alignItems: "flex-start",
    animation: "fadeIn 0.3s ease",
  },
  commentAvatar: {
    width: "32px",
    height: "32px",
    borderRadius: "50%",
    flexShrink: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "12px",
    fontWeight: "700",
    color: "#fff",
  },
  commentContent: {
    flex: 1,
    minWidth: 0,
  },
  commentUserRow: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    marginBottom: "4px",
  },
  commentUserName: {
    fontSize: "13px",
    fontWeight: "600",
    color: t.text.primary,
  },
  commentTime: {
    fontSize: "11px",
    color: t.text.tertiary,
  },
  commentBody: {
    fontSize: "13px",
    color: t.text.secondary,
    lineHeight: 1.55,
    backgroundColor: t.bg.primary,
    padding: "10px 14px",
    borderRadius: "12px",
    border: `1px solid ${t.border}`,
    borderBottomLeftRadius: "4px",
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
  },
});
