export const getStyles = (t, isDark) => ({
  container: {
    minHeight: '100vh',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: isDark ? '#090d16' : '#f8f6f3',
    padding: '20px',
    position: 'relative',
    overflow: 'hidden',
  },
  blob1: {
    width: '400px',
    height: '400px',
    background: isDark
      ? 'radial-gradient(circle, rgba(16,185,129,0.08) 0%, transparent 70%)'
      : 'radial-gradient(circle, rgba(16,185,129,0.06) 0%, transparent 70%)',
    top: '-120px',
    right: '-100px',
    position: 'absolute',
    borderRadius: '50%',
    pointerEvents: 'none',
    animation: 'float 8s ease-in-out infinite',
  },
  blob2: {
    width: '350px',
    height: '350px',
    background: isDark
      ? 'radial-gradient(circle, rgba(99,102,241,0.06) 0%, transparent 70%)'
      : 'radial-gradient(circle, rgba(99,102,241,0.04) 0%, transparent 70%)',
    bottom: '-80px',
    left: '-80px',
    position: 'absolute',
    borderRadius: '50%',
    pointerEvents: 'none',
    animation: 'floatReverse 10s ease-in-out infinite',
  },
  innerContainer: {
    display: 'flex',
    width: '100%',
    maxWidth: '920px',
    minHeight: '560px',
    borderRadius: '24px',
    overflow: 'hidden',
    position: 'relative',
    zIndex: 1,
    boxShadow: isDark
      ? '0 0 0 1px rgba(255,255,255,0.04), 0 25px 50px -12px rgba(0,0,0,0.5)'
      : '0 0 0 1px rgba(0,0,0,0.02), 0 25px 50px -12px rgba(0,0,0,0.08)',
    animation: 'scaleIn 0.5s ease-out',
  },
  leftPanel: {
    flex: '1',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    padding: '48px',
    background: isDark
      ? 'linear-gradient(160deg, #111827 0%, #064e3b 100%)'
      : 'linear-gradient(160deg, #1e293b 0%, #065f46 100%)',
    position: 'relative',
    overflow: 'hidden',
  },
  leftPattern: {
    position: 'absolute',
    inset: 0,
    opacity: isDark ? 0.03 : 0.05,
    backgroundImage: `url("data:image/svg+xml,%3Csvg width='60' height='60' viewBox='0 0 60 60' xmlns='http://www.w3.org/2000/svg'%3E%3Cg fill='none' fill-rule='evenodd'%3E%3Cg fill='%23ffffff' fill-opacity='1'%3E%3Cpath d='M36 34v-4h-2v4h-4v2h4v4h2v-4h4v-2h-4zm0-30V0h-2v4h-4v2h4v4h2V6h4V4h-4zM6 34v-4H4v4H0v2h4v4h2v-4h4v-2H6zM6 4V0H4v4H0v2h4v4h2V6h4V4H6z'/%3E%3C/g%3E%3C/g%3E%3C/svg%3E")`,
  },
  leftGlow: {
    position: 'absolute',
    width: '300px',
    height: '300px',
    borderRadius: '50%',
    background: 'radial-gradient(circle, rgba(52,211,153,0.12) 0%, transparent 70%)',
    top: '-80px',
    right: '-80px',
    pointerEvents: 'none',
    animation: 'float 7s ease-in-out infinite',
  },
  leftGlow2: {
    position: 'absolute',
    width: '200px',
    height: '200px',
    borderRadius: '50%',
    background: 'radial-gradient(circle, rgba(251,191,36,0.08) 0%, transparent 70%)',
    bottom: '-40px',
    left: '-40px',
    pointerEvents: 'none',
    animation: 'floatReverse 9s ease-in-out infinite',
  },
  leftContent: {
    position: 'relative',
    zIndex: 1,
  },
  leftBadge: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    padding: '4px 12px 4px 8px',
    borderRadius: '20px',
    background: 'rgba(255,255,255,0.08)',
    color: '#34d399',
    fontSize: '11px',
    fontWeight: '600',
    letterSpacing: '0.3px',
    marginBottom: '32px',
    backdropFilter: 'blur(8px)',
    border: '1px solid rgba(255,255,255,0.06)',
    textTransform: 'uppercase',
    animation: 'fadeIn 0.5s ease-out 0.1s both',
  },
  leftTitle: {
    fontSize: '32px',
    fontWeight: '800',
    color: '#ffffff',
    lineHeight: '1.15',
    margin: '0 0 12px',
    letterSpacing: '-0.5px',
    animation: 'slideUp 0.5s ease-out 0.2s both',
  },
  leftTitleAccent: {
    display: 'block',
    background: 'linear-gradient(135deg, #34d399, #10b981)',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
  },
  leftDesc: {
    fontSize: '14px',
    color: 'rgba(255,255,255,0.6)',
    lineHeight: '1.6',
    margin: '0 0 40px',
    maxWidth: '320px',
    animation: 'slideUp 0.5s ease-out 0.3s both',
  },
  leftFeature: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    marginBottom: '14px',
    color: 'rgba(255,255,255,0.7)',
    fontSize: '13px',
    fontWeight: '500',
    animation: 'fadeIn 0.4s ease-out both',
  },
  leftFeatureDot: {
    width: '6px',
    height: '6px',
    borderRadius: '50%',
    background: '#fbbf24',
    flexShrink: 0,
  },
  card: {
    width: '420px',
    backgroundColor: isDark ? '#111827' : '#ffffff',
    padding: '48px 40px',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    animation: 'slideUp 0.5s ease-out 0.15s both',
  },
  logoWrapper: {
    marginBottom: '32px',
    animation: 'fadeIn 0.5s ease-out 0.25s both',
  },
  logoRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    marginBottom: '20px',
  },
  logoIcon: {
    width: '36px',
    height: '36px',
    borderRadius: '10px',
    background: isDark ? '#1e293b' : '#f1f5f9',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    border: `1px solid ${isDark ? '#334155' : '#e2e8f0'}`,
    transition: 'transform 0.3s ease, box-shadow 0.3s ease',
  },
  logoText: {
    fontSize: '16px',
    fontWeight: '700',
    color: t.text.primary,
    letterSpacing: '-0.3px',
  },
  title: {
    fontSize: '20px',
    fontWeight: '700',
    color: t.text.primary,
    margin: '0 0 4px',
    letterSpacing: '-0.3px',
  },
  subtitle: {
    fontSize: '14px',
    color: t.text.secondary,
    margin: 0,
  },
  error: {
    padding: '10px 14px',
    borderRadius: '10px',
    marginBottom: '20px',
    backgroundColor: isDark ? 'rgba(239,68,68,0.08)' : '#fef2f2',
    border: `1px solid ${isDark ? 'rgba(239,68,68,0.15)' : '#fecaca'}`,
    color: t.danger,
    fontSize: '13px',
    fontWeight: '500',
    animation: 'fadeIn 0.3s ease-out',
  },
  formGroup: {
    marginBottom: '16px',
  },
  label: {
    display: 'block',
    fontSize: '12px',
    fontWeight: '600',
    color: t.text.secondary,
    marginBottom: '5px',
    textTransform: 'uppercase',
    letterSpacing: '0.3px',
  },
  inputWrapper: {
    position: 'relative',
  },
  inputIcon: {
    position: 'absolute',
    left: '12px',
    top: '50%',
    transform: 'translateY(-50%)',
    transition: 'color 0.2s ease',
    color: isDark ? '#94a3b8' : '#94a3b8',
  },
  eyeBtn: {
    position: 'absolute',
    right: '10px',
    top: '50%',
    transform: 'translateY(-50%)',
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    padding: '4px',
    display: 'flex',
    alignItems: 'center',
    color: isDark ? '#64748b' : '#94a3b8',
    transition: 'color 0.2s',
  },
  input: {
    width: '100%',
    padding: '11px 12px 11px 38px',
    borderRadius: '10px',
    border: `1.5px solid ${t.border}`,
    backgroundColor: isDark ? '#0f172a' : '#f8fafc',
    color: t.text.primary,
    fontSize: '14px',
    fontWeight: '500',
    boxSizing: 'border-box',
    transition: 'border-color 0.2s, box-shadow 0.2s, background-color 0.2s, transform 0.2s',
  },
  submitButton: (loading) => ({
    width: '100%',
    padding: '12px',
    borderRadius: '10px',
    border: 'none',
    background: isDark
      ? 'linear-gradient(135deg, #059669, #10b981)'
      : 'linear-gradient(135deg, #1e293b, #334155)',
    color: '#fff',
    fontSize: '14px',
    fontWeight: '600',
    cursor: loading ? 'not-allowed' : 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '8px',
    opacity: loading ? 0.7 : 1,
    marginTop: '8px',
    letterSpacing: '0.2px',
    overflow: 'hidden',
    position: 'relative',
    transition: 'opacity 0.2s, transform 0.2s, box-shadow 0.2s',
  }),
  footerText: {
    textAlign: 'center',
    marginTop: '28px',
    fontSize: '13px',
    color: t.text.tertiary,
  },
  link: {
    color: isDark ? '#34d399' : '#059669',
    fontWeight: '600',
    textDecoration: 'none',
    transition: 'color 0.2s',
  },
});