export const getStyles = (t, isDark) => ({
  container: {
    minHeight: '100vh',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: isDark
      ? 'linear-gradient(135deg, #0f172a 0%, #1e1b4b 50%, #0f172a 100%)'
      : 'linear-gradient(135deg, #eef2ff 0%, #e0e7ff 50%, #eef2ff 100%)',
    padding: '20px',
  },
  card: {
    width: '100%',
    maxWidth: '420px',
    backgroundColor: t.bg.secondary,
    borderRadius: '16px',
    border: `1px solid ${t.border}`,
    boxShadow: t.shadowXl,
    padding: '40px 32px',
    animation: 'fadeIn 0.4s ease',
  },
  logoWrapper: {
    textAlign: 'center',
    marginBottom: '32px',
  },
  logoIcon: {
    width: '56px',
    height: '56px',
    borderRadius: '14px',
    background: 'linear-gradient(135deg, #10b981, #059669)',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: '16px',
    boxShadow: '0 4px 14px rgba(16,185,129,0.3)',
  },
  title: {
    fontSize: '24px',
    fontWeight: '700',
    color: t.text.primary,
    margin: '0 0 4px',
  },
  subtitle: {
    fontSize: '14px',
    color: t.text.secondary,
    margin: 0,
  },
  error: {
    padding: '12px 16px',
    borderRadius: '10px',
    marginBottom: '20px',
    backgroundColor: isDark ? 'rgba(239,68,68,0.1)' : '#fef2f2',
    border: `1px solid ${isDark ? 'rgba(239,68,68,0.2)' : '#fecaca'}`,
    color: t.danger,
    fontSize: '13px',
    fontWeight: '500',
  },
  formGroup: {
    marginBottom: '16px',
  },
  label: {
    display: 'block',
    fontSize: '13px',
    fontWeight: '600',
    color: t.text.secondary,
    marginBottom: '6px',
  },
  inputWrapper: {
    position: 'relative',
  },
  inputIcon: {
    position: 'absolute',
    left: '12px',
    top: '50%',
    transform: 'translateY(-50%)',
  },
  input: {
    width: '100%',
    padding: '10px 12px 10px 40px',
    borderRadius: '10px',
    border: `1.5px solid ${t.border}`,
    backgroundColor: t.bg.input,
    color: t.text.primary,
    fontSize: '14px',
    boxSizing: 'border-box',
    transition: 'border-color 0.2s, box-shadow 0.2s',
  },
  submitButton: (loading) => ({
    width: '100%',
    padding: '12px',
    borderRadius: '10px',
    border: 'none',
    background: 'linear-gradient(135deg, #10b981, #059669)',
    color: '#fff',
    fontSize: '15px',
    fontWeight: '600',
    cursor: loading ? 'not-allowed' : 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '8px',
    opacity: loading ? 0.7 : 1,
    boxShadow: '0 4px 14px rgba(16,185,129,0.3)',
    transition: 'opacity 0.2s, transform 0.2s',
  }),
  footerText: {
    textAlign: 'center',
    marginTop: '24px',
    fontSize: '14px',
    color: t.text.secondary,
  },
  link: {
    color: t.accent,
    fontWeight: '600',
  },
});
