export const getStyles = (t, isDark) => ({
  container: {
    minHeight: '100vh',
    backgroundColor: t.bg.primary,
    padding: '30px',
    fontFamily: "'Poppins', sans-serif",
  },
  card: {
    backgroundColor: t.bg.secondary,
    padding: '40px',
    borderRadius: '16px',
    border: `1px solid ${t.border}`,
    boxShadow: t.shadowLg,
    maxWidth: '600px',
    margin: '0 auto',
    animation: 'fadeIn 0.3s ease',
  },
  backBtn: {
    padding: '8px 16px',
    backgroundColor: t.bg.tertiary,
    color: t.text.secondary,
    border: `1px solid ${t.border}`,
    borderRadius: '10px',
    cursor: 'pointer',
    fontSize: '13px',
    fontWeight: '600',
    marginBottom: '24px',
    transition: 'all 0.2s',
  },
  title: {
    color: t.text.primary,
    marginBottom: '28px',
    fontSize: '22px',
    fontWeight: '700',
    letterSpacing: '-0.3px',
  },
  form: {
    display: 'flex',
    flexDirection: 'column',
    gap: '20px',
  },
  formGroup: {
    display: 'flex',
    flexDirection: 'column',
  },
  label: {
    marginBottom: '6px',
    color: t.text.secondary,
    fontWeight: '600',
    fontSize: '12px',
    textTransform: 'uppercase',
    letterSpacing: '0.3px',
  },
  input: {
    padding: '11px 14px',
    border: `1.5px solid ${t.border}`,
    borderRadius: '10px',
    fontSize: '14px',
    fontFamily: "'Poppins', sans-serif",
    backgroundColor: isDark ? '#0f172a' : '#f8fafc',
    color: t.text.primary,
    fontWeight: '500',
    transition: 'border-color 0.2s, box-shadow 0.2s',
  },
  textarea: {
    padding: '11px 14px',
    border: `1.5px solid ${t.border}`,
    borderRadius: '10px',
    fontSize: '14px',
    fontFamily: "'Poppins', sans-serif",
    backgroundColor: isDark ? '#0f172a' : '#f8fafc',
    color: t.text.primary,
    fontWeight: '500',
    resize: 'vertical',
    minHeight: '100px',
    transition: 'border-color 0.2s, box-shadow 0.2s',
  },
  select: {
    padding: '11px 14px',
    border: `1.5px solid ${t.border}`,
    borderRadius: '10px',
    fontSize: '14px',
    fontFamily: "'Poppins', sans-serif",
    backgroundColor: isDark ? '#0f172a' : '#f8fafc',
    color: t.text.primary,
    fontWeight: '500',
    cursor: 'pointer',
    transition: 'border-color 0.2s, box-shadow 0.2s',
  },
  row: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '20px',
  },
  buttonGroup: {
    display: 'flex',
    gap: '10px',
    marginTop: '12px',
  },
  submitBtn: {
    padding: '12px 24px',
    backgroundColor: t.accent,
    color: '#fff',
    border: 'none',
    borderRadius: '10px',
    fontSize: '14px',
    fontWeight: '600',
    cursor: 'pointer',
    flex: 1,
    transition: 'opacity 0.2s, transform 0.2s',
  },
  cancelBtn: {
    padding: '12px 24px',
    backgroundColor: t.bg.tertiary,
    color: t.text.secondary,
    border: `1px solid ${t.border}`,
    borderRadius: '10px',
    fontSize: '14px',
    fontWeight: '600',
    cursor: 'pointer',
    flex: 1,
    transition: 'all 0.2s',
  },
  error: {
    backgroundColor: isDark ? 'rgba(239,68,68,0.08)' : '#fef2f2',
    color: t.danger,
    padding: '12px 14px',
    borderRadius: '10px',
    marginBottom: '20px',
    fontSize: '13px',
    fontWeight: '500',
    border: `1px solid ${isDark ? 'rgba(239,68,68,0.15)' : '#fecaca'}`,
  },
});