const styles = {
  column: {
    minWidth: '300px',
    backgroundColor: '#ffffff',
    borderRadius: '8px',
    borderTop: '4px solid',
    padding: '16px',
    boxShadow: '0 1px 3px rgba(0,0,0,0.1)',
    display: 'flex',
    flexDirection: 'column',
  },
  columnHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '16px',
    paddingBottom: '12px',
    borderBottom: '1px solid #eee',
  },
  columnTitle: {
    fontSize: '16px',
    fontWeight: '600',
    color: '#333',
    margin: 0,
  },
  ticketCount: {
    fontSize: '12px',
    fontWeight: 'bold',
    color: '#999',
    backgroundColor: '#f5f5f5',
    padding: '4px 8px',
    borderRadius: '12px',
  },
  cardsList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
    minHeight: '100px',
  },
  card: {
    backgroundColor: '#f9fafb',
    border: '1px solid #e5e7eb',
    borderRadius: '6px',
    padding: '12px',
    cursor: 'grab',
    transition: 'all 0.2s ease',
    boxShadow: '0 1px 2px rgba(0,0,0,0.05)',
  },
  priorityBadge: {
    display: 'inline-block',
    fontSize: '11px',
    fontWeight: 'bold',
    color: '#ffffff',
    padding: '4px 8px',
    borderRadius: '4px',
    marginBottom: '8px',
  },
  cardTitle: {
    fontSize: '14px',
    fontWeight: '600',
    color: '#1f2937',
    margin: '0 0 8px 0',
    wordBreak: 'break-word',
  },
  cardDescription: {
    fontSize: '12px',
    color: '#6b7280',
    margin: '0 0 8px 0',
    lineHeight: '1.4',
  },
  cardFooter: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    fontSize: '11px',
  },
  category: {
    color: '#9ca3af',
    backgroundColor: '#f3f4f6',
    padding: '2px 8px',
    borderRadius: '3px',
  },
};

export default styles;
