export const getStyles = (t, isEdit, loading) => ({
  backdrop: {
    position: 'fixed',
    inset: 0,
    zIndex: 1000,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(15, 23, 42, 0.4)',
    backdropFilter: 'blur(8px)',
    padding: '20px',
    animation: 'fadeIn 0.2s ease',
  },
  modal: {
    width: '100%',
    maxWidth: '520px',
    backgroundColor: t.bg.secondary,
    borderRadius: '16px',
    border: `1px solid ${t.border}`,
    boxShadow: '0 20px 25px -5px rgba(0, 0, 0, 0.15), 0 10px 10px -5px rgba(0, 0, 0, 0.04)',
    animation: 'slideUp 0.3s cubic-bezier(0.16, 1, 0.3, 1)',
    maxHeight: '90vh',
    overflowY: 'auto',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '20px 24px',
    borderBottom: `1px solid ${t.border}`,
  },
  title: {
    margin: 0,
    fontSize: '18px',
    fontWeight: '700',
    color: t.text.primary,
  },
  closeBtn: {
    width: '32px',
    height: '32px',
    borderRadius: '8px',
    border: 'none',
    backgroundColor: t.bg.tertiary,
    color: t.text.secondary,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    transition: 'all 0.15s ease',
  },
  form: {
    padding: '24px',
  },
  error: {
    padding: '10px 14px',
    borderRadius: '10px',
    marginBottom: '16px',
    backgroundColor: 'rgba(239,68,68,0.08)',
    border: '1px solid rgba(239,68,68,0.15)',
    color: t.danger,
    fontSize: '13px',
    fontWeight: '500',
  },
  formGroup: {
    marginBottom: '16px',
  },
  label: {
    display: 'block',
    fontSize: '13px',
    fontWeight: '600',
    color: t.text.secondary,
    marginBottom: '6px',
  },
  input: {
    width: '100%',
    padding: '10px 14px',
    borderRadius: '10px',
    border: `1.5px solid ${t.border}`,
    backgroundColor: t.bg.input,
    color: t.text.primary,
    fontSize: '14px',
    boxSizing: 'border-box',
    transition: 'border-color 0.2s, box-shadow 0.2s',
  },
  grid: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '16px',
    marginBottom: '16px',
  },
  assigneesSection: {
    marginBottom: '24px',
    position: 'relative',
  },
  dropdownTrigger: {
    width: '100%',
    padding: '10px 14px',
    borderRadius: '10px',
    border: `1.5px solid ${t.border}`,
    backgroundColor: t.bg.input,
    color: t.text.primary,
    fontSize: '13px',
    fontWeight: '600',
    boxSizing: 'border-box',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    cursor: 'pointer',
  },
  dropdownMenu: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: '100%',
    marginTop: '6px',
    backgroundColor: t.bg.secondary,
    border: `1.5px solid ${t.border}`,
    borderRadius: '12px',
    boxShadow: '0 10px 25px -5px rgba(0,0,0,0.15), 0 8px 10px -6px rgba(0,0,0,0.05)',
    zIndex: 100,
    padding: '12px',
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
  },
  dropdownSearchWrapper: {
    position: 'relative',
    width: '100%',
  },
  dropdownSearchIcon: {
    position: 'absolute',
    left: '10px',
    top: '50%',
    transform: 'translateY(-50%)',
    color: t.text.tertiary,
  },
  dropdownSearchInput: {
    width: '100%',
    padding: '7px 10px 7px 30px',
    borderRadius: '8px',
    border: `1.5px solid ${t.border}`,
    backgroundColor: t.bg.primary,
    color: t.text.primary,
    fontSize: '12px',
    boxSizing: 'border-box',
  },
  dropdownList: {
    maxHeight: '140px',
    overflowY: 'auto',
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  },
  dropdownItem: (isSelected) => ({
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '8px 10px',
    borderRadius: '8px',
    cursor: 'pointer',
    fontSize: '12px',
    fontWeight: '500',
    backgroundColor: isSelected ? t.accentLight : 'transparent',
    color: isSelected ? t.accent : t.text.primary,
    transition: 'all 0.15s ease',
  }),
  buttonGroup: {
    display: 'flex',
    gap: '10px',
    paddingTop: '8px',
  },
  cancelBtn: {
    flex: 1,
    padding: '11px',
    borderRadius: '10px',
    border: `1.5px solid ${t.border}`,
    backgroundColor: 'transparent',
    color: t.text.secondary,
    fontSize: '14px',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'all 0.15s ease',
  },
  submitBtn: {
    flex: 1,
    padding: '11px',
    borderRadius: '10px',
    border: 'none',
    background: 'linear-gradient(135deg, #6366f1, #8b5cf6)',
    color: '#fff',
    fontSize: '14px',
    fontWeight: '600',
    cursor: loading ? 'not-allowed' : 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '6px',
    opacity: loading ? 0.7 : 1,
    boxShadow: '0 4px 12px rgba(99,102,241,0.25)',
    transition: 'all 0.15s ease',
  },
});
