export const getStyles = (t, isEdit, loading) => ({
  backdrop: {
    position: 'fixed',
    inset: 0,
    zIndex: 1000,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(15, 23, 42, 0.4)',
    backdropFilter: 'blur(8px)',
    padding: '20px',
    animation: 'fadeIn 0.2s ease',
  },
  modal: {
    width: '100%',
    maxWidth: '520px',
    backgroundColor: t.bg.secondary,
    borderRadius: '16px',
    border: `1px solid ${t.border}`,
    boxShadow: '0 25px 50px -12px rgba(0, 0, 0, 0.25)',
    animation: 'slideUp 0.3s cubic-bezier(0.16, 1, 0.3, 1)',
    maxHeight: '90vh',
    overflowY: 'auto',
  },
  headerBar: {
    height: '4px',
    background: 'linear-gradient(90deg, #6366f1, #8b5cf6, #a78bfa)',
    borderRadius: '16px 16px 0 0',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '20px 24px 0',
  },
  headerLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
  },
  headerIcon: {
    width: '36px',
    height: '36px',
    borderRadius: '10px',
    backgroundColor: `${t.accent}15`,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: t.accent,
  },
  title: {
    margin: 0,
    fontSize: '17px',
    fontWeight: '700',
    color: t.text.primary,
    letterSpacing: '-0.3px',
  },
  subtitle: {
    fontSize: '12px',
    color: t.text.tertiary,
    marginTop: '2px',
  },
  closeBtn: {
    width: '32px',
    height: '32px',
    borderRadius: '8px',
    border: `1px solid ${t.border}`,
    backgroundColor: t.bg.tertiary,
    color: t.text.secondary,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    transition: 'all 0.15s ease',
  },
  form: {
    padding: '20px 24px 24px',
  },
  error: {
    padding: '10px 14px',
    borderRadius: '10px',
    marginBottom: '16px',
    backgroundColor: 'rgba(239,68,68,0.08)',
    border: '1px solid rgba(239,68,68,0.15)',
    color: t.danger,
    fontSize: '13px',
    fontWeight: '500',
  },
  sectionCard: {
    backgroundColor: t.bg.primary,
    borderRadius: '12px',
    padding: '16px',
    marginBottom: '16px',
    border: `1px solid ${t.border}`,
  },
  sectionLabel: {
    fontSize: '11px',
    fontWeight: '700',
    color: t.text.tertiary,
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
    marginBottom: '12px',
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
  },
  formGroup: {
    marginBottom: '14px',
  },
  formGroupLast: {
    marginBottom: 0,
  },
  label: {
    display: 'block',
    fontSize: '12px',
    fontWeight: '600',
    color: t.text.secondary,
    marginBottom: '5px',
  },
  input: {
    width: '100%',
    padding: '10px 14px',
    borderRadius: '10px',
    border: `1.5px solid ${t.border}`,
    backgroundColor: t.bg.input,
    color: t.text.primary,
    fontSize: '13px',
    fontWeight: '500',
    boxSizing: 'border-box',
    transition: 'border-color 0.2s, box-shadow 0.2s',
    fontFamily: 'inherit',
  },
  textarea: {
    width: '100%',
    padding: '10px 14px',
    borderRadius: '10px',
    border: `1.5px solid ${t.border}`,
    backgroundColor: t.bg.input,
    color: t.text.primary,
    fontSize: '13px',
    fontWeight: '500',
    boxSizing: 'border-box',
    resize: 'vertical',
    minHeight: '70px',
    fontFamily: 'inherit',
    lineHeight: '1.5',
    transition: 'border-color 0.2s, box-shadow 0.2s',
  },
  grid: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '12px',
  },
  selectWrapper: {
    position: 'relative',
  },
  selectTrigger: {
    width: '100%',
    padding: '10px 14px',
    borderRadius: '10px',
    border: `1.5px solid ${t.border}`,
    backgroundColor: t.bg.input,
    color: t.text.primary,
    fontSize: '13px',
    fontWeight: '500',
    boxSizing: 'border-box',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    cursor: 'pointer',
    fontFamily: 'inherit',
    transition: 'border-color 0.2s',
  },
  selectMenu: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: '100%',
    marginTop: '4px',
    backgroundColor: t.bg.secondary,
    border: `1.5px solid ${t.border}`,
    borderRadius: '12px',
    boxShadow: '0 10px 25px -5px rgba(0,0,0,0.15), 0 8px 10px -6px rgba(0,0,0,0.05)',
    zIndex: 101,
    overflow: 'hidden',
    padding: '6px',
    display: 'flex',
    flexDirection: 'column',
    gap: '2px',
  },
  selectOption: (active) => ({
    padding: '8px 12px',
    borderRadius: '8px',
    cursor: 'pointer',
    fontSize: '12px',
    fontWeight: active ? '600' : '500',
    color: active ? t.accent : t.text.primary,
    backgroundColor: active ? `${t.accent}12` : 'transparent',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    transition: 'all 0.12s ease',
  }),
  selectOptionDot: (color) => ({
    width: '8px',
    height: '8px',
    borderRadius: '50%',
    backgroundColor: color,
    flexShrink: 0,
  }),
  statusSection: {
    marginBottom: '16px',
  },
  assigneesSection: {
    position: 'relative',
  },
  dropdownTrigger: {
    width: '100%',
    padding: '10px 14px',
    borderRadius: '10px',
    border: `1.5px solid ${t.border}`,
    backgroundColor: t.bg.input,
    color: t.text.primary,
    fontSize: '13px',
    fontWeight: '500',
    boxSizing: 'border-box',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    cursor: 'pointer',
    fontFamily: 'inherit',
    transition: 'border-color 0.2s',
  },
  dropdownMenu: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: '100%',
    marginTop: '4px',
    backgroundColor: t.bg.secondary,
    border: `1.5px solid ${t.border}`,
    borderRadius: '12px',
    boxShadow: '0 10px 25px -5px rgba(0,0,0,0.15), 0 8px 10px -6px rgba(0,0,0,0.05)',
    zIndex: 100,
    overflow: 'hidden',
  },
  dropdownSearchWrapper: {
    position: 'relative',
    padding: '10px 10px 0',
  },
  dropdownSearchIcon: {
    position: 'absolute',
    left: '20px',
    top: '22px',
    transform: 'translateY(-50%)',
    color: t.text.tertiary,
  },
  dropdownSearchInput: {
    width: '100%',
    padding: '8px 10px 8px 30px',
    borderRadius: '8px',
    border: `1.5px solid ${t.border}`,
    backgroundColor: t.bg.primary,
    color: t.text.primary,
    fontSize: '12px',
    boxSizing: 'border-box',
    fontFamily: 'inherit',
  },
  dropdownList: {
    maxHeight: '150px',
    overflowY: 'auto',
    padding: '6px',
    display: 'flex',
    flexDirection: 'column',
    gap: '2px',
  },
  dropdownItem: (isSelected) => ({
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '8px 10px',
    borderRadius: '8px',
    cursor: 'pointer',
    fontSize: '12px',
    fontWeight: '500',
    backgroundColor: isSelected ? `${t.accent}12` : 'transparent',
    color: isSelected ? t.accent : t.text.primary,
    transition: 'all 0.15s ease',
  }),
  buttonGroup: {
    display: 'flex',
    gap: '10px',
    paddingTop: '16px',
    borderTop: `1px solid ${t.border}`,
    marginTop: '8px',
  },
  cancelBtn: {
    flex: 1,
    padding: '11px',
    borderRadius: '10px',
    border: `1.5px solid ${t.border}`,
    backgroundColor: 'transparent',
    color: t.text.secondary,
    fontSize: '13px',
    fontWeight: '600',
    cursor: 'pointer',
    fontFamily: 'inherit',
    transition: 'all 0.15s ease',
  },
  submitBtn: {
    flex: 1,
    padding: '11px',
    borderRadius: '10px',
    border: 'none',
    backgroundColor: t.accent,
    color: '#fff',
    fontSize: '13px',
    fontWeight: '600',
    cursor: loading ? 'not-allowed' : 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '6px',
    opacity: loading ? 0.7 : 1,
    fontFamily: 'inherit',
    transition: 'all 0.15s ease',
  },
});